### PR TITLE
Enhancement: Instruction display and markdown

### PR DESCRIPTION
**Pull request by caseydwyer**
This PR allows instructions to render markdown correctly, bringing the actual behavior in line with the config field help-text and Statamic's native field behavior _(see blue brackets below)_. 

It also fixes an issue where the instructions were "leaking" into the original header, as they weren't included in the `display: none;` rule _(see orange bracket below)_. 

Thanks for your work on this package, @eminos! 👍 Let me know if you'd like to see any edits, here. **Note: I did not build assets for updated JS & CSS; wasn't sure if you had a process or action in place for that...but happy to add them in here, if not!**

### Before:

image

### After:

image

### CODE REVIEW

**Comment by eminos** [comment]
@caseydwyer 
This is awesome. My first incoming PR!
Thank you Casey!
I just fixed one issue I noticed with nested P tags (since the P tag had the v-html attribute, instead of the parent DIV), and built the assets.

**Comment by caseydwyer** [comment]
Haha, sweet—happy to contribute the inaugural bits! 😄 Good catch on that `v-html` location...I kinda wondered about that, but ultimately decided to just follow Statamic's lead. The div is probably the right move. 👍 Thanks again!

**Comment by eminos** [comment]
It's a div in Statamics code as well.
https://github.com/statamic/cms/blob/aecdc10f3127a55c12b4467e08d592b828c751a4/resources/js/components/publish/Field.vue#L48C13-L51C41

**Comment by caseydwyer** [comment]
Ahh, sure enough! I think I was looking at [the `Sections.vue` component](https://github.com/statamic/cms/blob/aecdc10f3127a55c12b4467e08d592b828c751a4/resources/js/components/publish/Sections.vue#L8).

**Pull request merged**
